language: android

env:
  global:
    - ADB_INSTALL_TIMEOUT=16
    - TERM=dumb

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-22.1.0

    # The SDK version used to compile your project
    - android-22

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-22

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s WXGA800-7in
  - emulator -avd test -no-skin -no-audio -no-window -scale 0.5 &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - adb -e logcat *:W | tee logcat.log > /dev/null 2>&1 &

script:
  #- gradle connectedCheck
  - ./gradlew --info --continue connectedCheck coveralls
  - echo finshed

after_script:


# http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2


